version: "3.9"

services:
  db:
    image: postgres:15
    container_name: support_bot_db
    environment:
      POSTGRES_USER: support_bot_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: support_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    container_name: support_bot
    depends_on:
      - db
    environment:
      BOT_TOKEN: 8102068730:AAGFLI5vu0rCR_sCH0Y5a8nCjCkubkJ-Mms
      OWNER_ID: 7622191579
      DATABASE_USER: support_bot_user
      DATABASE_PASS: yourpassword
      DATABASE_HOST: db
      DATABASE_NAME: support_bot_db

volumes:
  postgres_data:
